### ISSUE TITLE
Yarn cache folder says `ENOENT: no such file or directory`

### ISSUE THREAD

**Issue by igorbrites** [reproducible-containers/buildkit-cache-dance#43]
I am adding this action to some NodeJS pipelines, though I'm unable to make it work with the Yarn cache as I did with Maven. I've tried using the default directory, pre-creating new ones, inside `/tmp`, using root and node users, and no luck so far.

Dockerfile:

```dockerfile
FROM node:18.14-alpine AS build

ENV YARN_CACHE_FOLDER=/tmp/.cache/yarn
WORKDIR /workspace/app
COPY package.json yarn.lock .eslintrc.json ./

RUN --mount=type=cache,target=/tmp/.cache/yarn yarn install

# ... rest of the file
```

Pipeline:

```yaml
name: Build
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
  
    - name: Download cache
      uses: actions/cache@v4
      id: cache
      with:
        path: cache-dir
        key: ${{ runner.os }}-nodejs-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-nodejs-${{ hashFiles('**/yarn.lock') }}
          ${{ runner.os }}-nodejs-

    - name: Inject cache into Docker
      uses: reproducible-containers/buildkit-cache-dance@v3.1.2
      with:
        skip-extraction: ${{ steps.cache.outputs.cache-hit }}
        cache-map: |
          {
            "cache-dir": "/tmp/.cache/yarn"
          }

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}:${{ env.SHA }}
          ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}:latest
```

Logs (resumed):

```
Cache not found for input keys: Linux-nodejs-c14da139bbf7ef2bf4632456bd01af76ca58aab28f63a2c1ddc8fe8cf69ba7c8, Linux-nodejs-c14da139bbf7ef2bf4632456bd01af76ca58aab28f63a2c1ddc8fe8cf69ba7c8, Linux-nodejs-
Run reproducible-containers/buildkit-cache-dance@v3.1.2
FROM busybox:1
COPY buildstamp buildstamp
RUN --mount=type=cache,target=/tmp/.cache/yarn     --mount=type=bind,source=.,target=/var/dance-cache     cp -p -R /var/dance-cache/. /tmp/.cache/yarn  || true

...

#19 [linux/amd64 build 6/8] RUN --mount=type=cache,target=/tmp/.cache/yarn yarn install
#19 0.211 yarn install v1.22.19
#19 0.303 [1/4] Resolving packages...
#19 0.909 [2/4] Fetching packages...
#19 1.226 error https://registry.yarnpkg.com/@babel/eslint-parser/-/eslint-parser-7.21.3.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, stat '/tmp/.cache/yarn/v6/npm-@babel-eslint-parser-7.21.3-d79e822050f2de65d7f368a076846e7184234af7-integrity/node_modules/@babel/eslint-parser/lib/utils/eslint-version.cjs'"
#19 1.226 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
