### ISSUE TITLE
tar error during post job cleanup

### ISSUE THREAD

**Issue by dataviruset** [reproducible-containers/buildkit-cache-dance#54]
On a self-hosted runner, arm64 macOS, Docker Desktop installed.

```
      - name: Build package cache
        id: cache
        uses: actions/cache@v4
        with:
          path: pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Metro cache
        id: metro-cache
        uses: actions/cache@v4
        with:
          path: metro-cache
          key: metro-cache-${{ runner.os }}-${{ inputs.image_name }}
      - name: inject cache
        uses: reproducible-containers/buildkit-cache-dance@v3
        with:
          cache-map: |
            {
              "pnpm-store": "/pnpm/store",
              "metro-cache": "/app/${{ inputs.app_dir }}/node_modules/.cache"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}
```

```
Post job cleanup.

FROM ghcr.io/containerd/busybox:latest
COPY buildstamp buildstamp
RUN --mount=type=cache,target=/pnpm/store     mkdir -p /var/dance-cache/     && cp -p -R /pnpm/store/. /var/dance-cache/ || true

tar: Must specify one of -c, -r, -t, -u, -x
Error: process exited with code 1
    at ChildProcess.<anonymous> (file:///Users/redacted/actions-runner3/_work/_actions/reproducible-containers/buildkit-cache-dance/v3/dist/index.js:7129:36)
    at ChildProcess.emit (node:events:524:28)
    at maybeClose (node:internal/child_process:1104:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)
Error: process exited with code 1
    at ChildProcess.<anonymous> (file:///Users/redacted/actions-runner3/_work/_actions/reproducible-containers/buildkit-cache-dance/v3/dist/index.js:7129:36)
    at ChildProcess.emit (node:events:524:28)
    at maybeClose (node:internal/child_process:1104:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

Could it be that something changed in the latest busybox to make the tar command stop working?
